# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
  db_driver: orm # or mongodb or phpcr
  mappings:
    ingredient_images:
      uri_prefix:         '%app.path.ingredient_images%'
      upload_destination: '%kernel.project_dir%/public%app.path.ingredient_images%'
    dish_images:
      uri_prefix:         '%app.path.dish_images%'
      upload_destination: '%kernel.project_dir%/public%app.path.dish_images%'
    dish_step_images:
      uri_prefix:         '%app.path.dish_step_images%'
      upload_destination: '%kernel.project_dir%/public%app.path.dish_step_images%'
