version: '3.6'

networks:
  reslim_api_dev:
    name: reslim_api_dev
    driver: bridge

services:
  web:
    container_name: api-web
    build:
      context: ./dockerfiles/app/dev/nginx
      dockerfile: Dockerfile
    volumes:
      - ./dockerfiles/app/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html:ro
    ports:
      - "${NGINX_PORT}:80"
    external_links:
      - api-php-fpm
    networks:
      - reslim_api_dev

  php-fpm:
    container_name: api-php-fpm
    hostname: php-fpm.docker
    build:
      context: ./dockerfiles/app/dev/php-fpm
      dockerfile: Dockerfile
      args:
        HOST_UID: ${HOST_UID:?specify HOST_UID in ./.env file}
    environment:
      XDEBUG_CONFIG: remote_port=9000 idekey="PHPSTORM"
      PHP_IDE_CONFIG: serverName=api
    volumes:
      - ./:/var/www/html
      - ./dockerfiles/app/dev/php-fpm/php-fpm.conf:/etc/php-fpm.conf
      - ./dockerfiles/app/dev/php-fpm/www.conf:/etc/php-fpm.d/www.conf
      - ./dockerfiles/app/dev/php-fpm/php.ini:/usr/local/etc/php/php.ini
    networks:
      - reslim_api_dev

  api-db:
    image: postgres
    restart: always
    volumes:
      - ./docker/db/:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - reslim_api_dev